plugins {
    id 'idea'
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

base {
    archivesName = "${mod_name}-fabric-${minecraft_version}"
}

repositories{
    maven {
        url = "https://mvn.devos.one/snapshots"
    }// Create and several dependencies
    maven {
        url = "https://mvn.devos.one/releases"
    } // Porting Lib releases
    maven {
        url = "https://maven.jamieswhiteshirt.com/libs-release"
    } // Reach Entity Attributes
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly project(":Common")
    compileOnly project(":CreateSupportCommon")

    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.5.1"//source: https://github.com/Fuzss/forgeconfigapiport-fabric

    modCompileOnly "curse.maven:ftbranks-472659:6431745"//home: https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-fabric
    modCompileOnly "curse.maven:architectury-419699:5786326"//home: https://www.curseforge.com/minecraft/mc-mods/architectury-api
    modCompileOnly "curse.maven:ftblibrary-438495:7746958"//home: https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric

    modCompileOnly "net.luckperms:api:5.4"//source: https://github.com/LuckPerms/LuckPerms
    modCompileOnly 'me.lucko:fabric-permissions-api:0.2-SNAPSHOT'//source: https://github.com/lucko/fabric-permissions-api

    modCompileOnly "earth.terrarium.prometheus:prometheus-fabric-1.20.4:1.4.2"//source: https://github.com/terrarium-earth/Prometheus
    modCompileOnly "earth.terrarium.argonauts:argonauts-fabric-1.20.4:1.2.4"//source: https://modrinth.com/mod/odyssey-allies

    modCompileOnly "curse.maven:ftbteams-438497:7878280"//home: https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric
    modCompileOnly("com.simibubi.create:create-fabric-1.20.1:${fabric_create_version}"){
        exclude(group: "com.jozufozu.flywheel")
        exclude(group: "net.minecraftforge")
    }
}

loom {
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
            //vmArg("-Dmixin.debug.export=true")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}


processResources {
    from project(":Common").sourceSets.main.resources
    from project(":CreateSupportCommon").sourceSets.main.resources
    inputs.property "version", project.version
    exclude "META-INF/*_core.js"
    exclude "META-INF/coremods.json"
}


tasks.withType(JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
    source(project(":CreateSupportCommon").sourceSets.main.allSource)
}

packageSources {
    from(project(":CreateSupportCommon").sourceSets.main.allSource)//normal common project gets included by default but not this
}

jar {
    from("LICENSE") {
        rename { "${it}_${mod_name}" }
    }
}

jar.finalizedBy('packageSources')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
            artifact packageSources
        }
    }
}
