# Project
version=0.31.3
group=xaero.pac

# Common
minecraft_version=1.20.1
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
license=GNU Lesser General Public License v3.0 (LGPL-3.0-only)

# Forge
forge_version=47.4.22
//forge_ats_enabled=true
forge_minecraft_version_range=[1.20, 1.20.1]
forge_loader_version_range=[46,)
forge_version_range=[47.0.28,)

# Fabric
fabric_version=0.92.0+1.20.1
fabric_loader_version=0.15.11
fabric_loader_version_range=>=0.14
minecraft_version_range=>=1.20 <=1.20.1

# NeoForge
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)

# Deps
forgeconfigapiport_fabric_range=*
fabric_extension_create_breaks_range=*
fabric_api_range=*
java_fabric_range=>=17
create_forge_range=[6.0.0,)
fabric_create_version=6.0.4.0+mc1.20.1-build.1673
forge_create_version=6.0.6-150
forge_ponder_version=1.0.80
forge_flywheel_version=1.0.4
forge_registrate_version=MC1.20-1.3.3

# Mod options
mod_name=open-parties-and-claims
mod_author=Xaero96
mod_id=openpartiesandclaims
mod_display_name=Open Parties and Claims
description=This mod adds the ability to claim and to forceload world chunks, as well as create and manage player parties. It also gives server owners powerful controls over their players' usage of the mod's features.\\nThe mod's API allows other mods or plugins to easily interact with the parties and the chunk claims, both on the server and the client side.\\nXaero's Minimap mod and World Map mods are recommended in order to fully experience everything that this mod has to offer.
homepage=https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims
sources=https://github.com/thexaero/open-parties-and-claims
issues=https://github.com/thexaero/open-parties-and-claims/issues

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false